### ISSUE TITLE
Missing comma in win32 executable template list

### ISSUE THREAD

**Issue by bsilvaLS** [diegogarciahuerta/tk-clarisse#2]
In `setup.py`, there's a missing comma in the `EXECUTABLE_TEMPLATES` literal preventing Shotgun from resolving the Clarisse path correctly in win32:

https://github.com/diegogarciahuerta/tk-clarisse/blob/61b4692c51c849baeb337a7326f0adb785481ec3/startup.py#L52-L56

**Comment by diegogarciahuerta** [comment]
Sorry for the delay, issue was resolved in this commit #3 . Closing Issue
